Revert "OEM対応"
This reverts commit 71e510fc4a07429738811939c71b2a18dd1d4a08.

Terraform applyでエラー

以下のエラーがでて追えないのでもとに戻す
Error: No matching records found